substitutions:
  _IMAGE: us-central1-docker.pkg.dev/project-30329891-0f8f-4493-928/workroom/workroom-bg-worker:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.worker
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY
