-- Live assistant: kill the peer-question recycling loop.
--
-- The previous design copied every `meeting_assistant_event` of kind `suggested_question` into
-- `deal_intel.similar_deal_question_template` and then re-served those rows via cosine match
-- on future meetings as `provenance: 'similar_company'`. With no quality signal in the seed,
-- bot-generated junk (assumption-inversion templates, contradiction restates, generic memo
-- prompts) became the source of truth for "peer questions" and produced low-quality cards
-- like "What evidence would invalidate the external dependency behind: '...'".
--
-- We drop the entire storage layer (table, FK, matcher RPC) and replace the runtime path
-- with a per-meeting LLM call grounded in real claims + this user's actually-asked questions
-- (`meeting_question_span.linked_tracked_question_id`). New cards use the renamed provenance
-- `peer_style`, added below for forward use; legacy `similar_company` rows remain in
-- `meeting_tracked_question` and render with the same badge via a UI alias.

drop function if exists public.deal_intel_match_similar_deal_question_templates(uuid[], extensions.vector(768), int);
drop function if exists deal_intel.match_similar_deal_question_templates(uuid[], extensions.vector(768), int);

alter table deal_intel.meeting_tracked_question
  drop constraint if exists meeting_tracked_question_template_id_fkey;
alter table deal_intel.meeting_tracked_question
  drop column if exists template_id;

drop table if exists deal_intel.similar_deal_question_template;

-- New provenance for cards generated by the per-meeting LLM, distinct from the historical
-- `similar_company` value which kept the literal-template semantics. Postgres enums can't
-- easily drop values, so we leave `similar_company` in place (no new code emits it).
do $$ begin
  alter type deal_intel.meeting_question_provenance add value if not exists 'peer_style';
exception
  when duplicate_object then null;
end $$;
